### ISSUE TITLE
Tailwind CSS v2.0

### ISSUE THREAD

**Issue by jaysonvaughn** [elimintz/justpy#170]
Is there an easy way to update the tw_dict as new versions of Tailwind are released?  Also, see below for those of us who have purchased tailwind ui.  

https://tailwindui.com/changes-for-v2
"Tailwind UI for Tailwind CSS v2.0 relies solely on the default Tailwind configuration, with certain examples also requiring first-party plugins like @tailwindcss/typography, @tailwindcss/aspect-ratio, or the new @tailwindcss/forms plugin."

Just looking for the best route to use the newest tailwind features.

Thank you

**Comment by elimintz** [comment]
I also use Tailwind extensively and love it. The update of tw_dict will have to wait for a new version (unless of course you want to take the task on...)
In order to use the latest version of Tailwind add:
```
NO_INTERNET = False
```

to justpy.env

This will fetch the latest version of all libraries from the web instead of using the version that comes with JustPy.
You can then use all the new classes but the justpy functions that deal with changing classes will not work for all classes (that requires changing tw_dict).

For tailwindui, there is an undocumented template option that you can use:
```python
wp = jp.WebPage(template_file='tailwindui.html')
```

This adds support for the tailwindui classes.

Let me know how it goes.

**Comment by jaysonvaughn** [comment]
I did find template_file='tailwindui.html' and also found it referenced in the documentation for Inter font.  
https://justpy.io/how_to/change_font/. That works well.  

The tailwind ui specific classes have gone away as of tailwind 2.0 and they have added some features as plugins.  I'll see if I can make the required changes.  Thank for the help and all the work on this project.

**Comment by VisitingOcean** [comment]
Do you have an ETA on when Tailwind 2.0 will be supported?

I tried the `NO_INTERNET` flag in the .env, but it grabbed Tailwind 1.4.6 rather than 2.x

**Comment by elimintz** [comment]
My bad, I didn't realize that unpkg does not get the latest version, just the latest version of the major version number specified.
I do not have a release date yet but expect it to be this month. 

In the meantime, this should work. Please add the following to your pages:
```python
wp.head_html = """
                <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2.0/dist/base.min.css">
                <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2.0/dist/components.min.css">
                <link rel="stylesheet" href="https://unpkg.com/@tailwindcss/typography/dist/typography.min.css">
                <link rel="stylesheet" href="https://unpkg.com/tailwindcss@^2.0/dist/utilities.min.css">
"""
```
For reference: https://justpy.io/reference/webpage/#head_html-and-body_html
Let me know if this does not work.

**Comment by WolfgangFahl** [comment]
https://tailwindcss.com is a moving target and handling such moving targets might be a separate issue
