### ISSUE TITLE
Components in Div

### ISSUE THREAD

**Issue by mdelmans** [elimintz/justpy#6]
Awesome project, thanks.

A nice feature would be to set components of a Div during initialisation, e.g.

```python
def hello_world():
    wp = jp.WebPage()
    jp.Div(
        components=[
            jp.P(text="hello")
        ],
        a=wp
    )
    return wp
```

**Comment by elimintz** [comment]
Thank you.

I think there is no need for this since you can do the following and it looks more Pythonic to me:

`import justpy as jp

def hello_world():
    wp = jp.WebPage()
    jp.Div(a=wp).add(*[jp.P(text=f"{i}) hello") for i in range(100)])
    return wp

jp.justpy(hello_world)`

The `add` method can accept any number of arguments.

**Comment by maciejmatczak** [comment]
@mdelmans , If you would like to keep the hierarchical notation of elements (similar to html), you could try something like:
```python
class myDiv(jp.Div):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

    def add(self, *args):
        for component in args:
            self.add_component(component)

        return self


def hello_world():
    wp = jp.WebPage().add(
        myDiv().add(
            jp.P(text='Hello'),
            jp.P(text='World')
        )
    )

    return wp
```

I needed to add `MyDiv`, since default `add` do not `return self`, like rest of the methods (`add_component` for example). It's like nestable almost fluent interface.

@elimintz, what do you think about adding `return self` for the rest of the methods?

**Comment by elimintz** [comment]
Sorry I noticed your comment just now.. 

What you suggest is the right way to go. I will add `return self` to the add method of Div.
