### ISSUE TITLE
Using component.delete() before parent_component.delete_components yields KeyError

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#72]
I was trying to remove a list item from a QList. Not knowing the recommended procedure I assumed that list_item.delete() would do the trick. 
However calling list.delete_components() a little later gave a KeyError. See below. 

It seems one has to remove the component before deleting it? 
```
            comp.a.remove_component(self)
            self.delete()
```

Bit confused that there is a delete_components method but no remove_components. There is a delete method but no remove method. 
So the actual question is: how does one dynamically add and remove components in the JustPythonic way?

```
DEBUG:    Traceback (most recent call last):
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/justpy.py", line 307, in handle_event
    event_result = await c.run_event_function(event_data['event_type'], event_data, True)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/htmlcomponents.py", line 335, in run_event_function
    event_result = await event_function(function_data)
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/list_app/main.py", line 17, in right_slide_click
    msg.page.construct_user_list()
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/list_app/main.py", line 66, in construct_user_list
    self.user_list.delete_components()
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/htmlcomponents.py", line 568, in delete_components
    c.delete()
  File "/Users/mjm/Dropbox/Devel/_Experiments/JustPy/venv/lib/python3.7/site-packages/justpy/htmlcomponents.py", line 554, in delete
    JustpyBaseComponent.instances.pop(self.id)
KeyError: 2
```

**Comment by elimintz** [comment]
There is a difference between remove and delete. Remove is just basically:

    self.components.remove(component)

It does not remove the component (an instance of a Python class) from memory, only from the list of components of some other component. 

Delete removes all references within JustPy to an instance so that the Python garbage collection can reclaim its memory.

When you delete a component before removing it from its parent's component list, you remove all references to it from the internal JustPy data structures but a reference remains in its parent's component list. The error occurs because delete_components is trying to delete a component that already has been deleted.

If this is not clear enough please let me know.

**Comment by mjmare** [comment]
Please give some recommendations on how to properly dynamically add/remove components. 
When should one remove, when delete?

**Comment by knoxvilledatabase** [comment]
@mjmare, does the example I gave you with the messages and feed app (https://github.com/elimintz/justpy/issues/64) not satisfy your requirements? In that app, we dynamically add and remove components.

**Comment by elimintz** [comment]
1) The framework automatically deletes all components on a page when a browser tab with displaying the page is closed  (unless the delete_flag is set to False). So one option is instead of removing elements set their `show` attribute to False and then they will be deleted by the framework when the browser tab closes.

2) If you remove an element from a page, and it closes later, it will not be deleted automatically. So you may first want to remove it and then delete it. In most use cases the memory leak is small so unless you have huge traffic you don't need to worry about deleting components until you see a problem emerging. The worst case is you need to restart the server more often.

3) The delete method also deletes all components the component contains, so you don't need to delete them separately (again, unless a child component as the delete_flag set to False).

Note: Only components that the user interacts with or contain components that user interacts with need to deleted because otherwise the framework does not include any reference to them. The components that need deletion  include components that explicitly have been assigned an event (like click for a button) or any component that has an input event to which the framework assigns an event even if the user doesn't (in order to update the value of the component on the server side in the before event handler).

I would be happy to help with the specific issue you have encountered if you like.

**Comment by mjmare** [comment]
@elimintz @knoxvilledatabase Thanks for the explanation. Please consider adding it to the docs.

**Comment by giodegas** [comment]
given an array of buttons in a page, is it possible to delete one after is pressed and have the page update without that button?

**Comment by elimintz** [comment]
Sure, there are many ways to do this, here is one way:

```python
import justpy as jp

button_classes = 'm-2 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full'

def remove_button(self, msg):
    msg.page.button_div.components.remove(self)

def delete_button_test():
    wp = jp.WebPage()
    wp.button_div = jp.Div(a=wp)
    for i in range(1,11):
        jp.Button(text=f'Button {i}', a=wp.button_div, classes=button_classes, click=remove_button)
    return wp

jp.justpy(delete_button_test)
```

If something in the example is not clear, please let me know
