### ISSUE TITLE
QDrawer does not honour model

### ISSUE THREAD

**Issue by mjmare** [elimintz/justpy#73]
I expected the QDrawer to supports the toggle method to control its visibility (https://quasar.dev/layout/drawer).
Of course, I do not know the policy on which methods are and which are not supported.  

(As a workaround I used model to control the visibility, but that is more verbose.)

**Comment by elimintz** [comment]
The `run_method` allows you to run any method https://justpy.io/quasar_tutorial/introduction/#running-quasar-component-methods

Currently to get the functionality you want you would have to create your  QDrawer derived class and add the following method to it:

```python
class MyQDrawer(jp.QDrawer):

    async def toggle(self, msg):
        await self.run_method('toggle()', msg.websocket)
```

Now use MyQDrawer instead and you should have what you need. Let me know if this doesn't work.

I agree that it is a good idea to have this for all quasar components as part of the framework. I'll do this in stages since there are tons of methods to support.

**Comment by mjmare** [comment]
Ah, that's good to know. Thanks.

**Comment by mjmare** [comment]
For the moment I'd think that this would would work. It doesn't:

```
class LayoutPage(jp.QuasarPage):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.data = {'left': True}

        self.layout = jp.QLayout(view='hHh lpR fFf', a=self)
        self.header = jp.QHeader(elevated=True, classes='bg-primary text-white', a=self.layout)
        self.toolbar = jp.QToolbar(a=self.header)

        async def click_btn(comp, msg):
            # self.data['left'] = not self.data['left']
            await self.drawer.run_method('toggle()', msg.websocket)

        c4 = jp.QBtn(dense=True, flat=True, round=True, icon='menu', click=click_btn, a=self.toolbar)

        c5 = jp.QToolbarTitle(a=self.toolbar)
        c6 = jp.QAvatar(a=c5)
        c7 = jp.Img(src='https://cdn.quasar.dev/logo/svg/quasar-logo.svg', a=c6, text='Title')

        self.drawer = jp.QDrawer(show_if_above=True, side='left', bordered=True, a=self.layout)

```
The button click handler is called (verified).

**Comment by elimintz** [comment]
Thank you for flagging this.  

In order to make this work, you just need to add `temp=False` to the definition of `self.drawer`:
```
self.drawer = jp.QDrawer(show_if_above=True, side='left', bordered=True, a=self.layout, temp=False)

```

This forces JustPy to generate an id for the element without which run_method does not work. 

The documentation of run_method is incomplete and I apologize I forgot to mention this to you in my previous answer. I will update the docs.

**Comment by mjmare** [comment]
Yes that works. Thx.
You might want to consider renaming the temp argument to something less common and more descriptive, like gen_id or generate_id (or whatever it really means).

**Comment by elimintz** [comment]
Yes, I'll do that (without removing temp so as not to break current programs).

In the initial development stages of JustPy the framework generated ids for all elements and had a reference to them in the internal data structures. But I soon realized that only elements that you need to interact with need an id and a reference. That saved a lot of memory and complexity. The temp name is a leftover from those experiments.

**Comment by mjmare** [comment]
Now you can still afford breaking things ;-) It's still v0.10
