### ISSUE TITLE
QInput keyup no longer receiving value

### ISSUE THREAD

**Issue by knoxvilledatabase** [elimintz/justpy#83]
In version 0.1.0 this worked, when I would start typing the options would filter based on keyup:

```
class QSelectWithFilter(jp.QSelect):

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        print('We are in QSelectWithFilter, here is the model:')
        # print(kwargs.get('model', 'dont have a model'))
        self.initial_options = kwargs.get('options', [])
        self.use_input = True
        self.allowed_events = ['input', 'remove', 'add', 'new_value', 'filter', 'filter_abort', 'keyup', 'focus', 'blur']
        self.on('keyup', self.filter_function)

    def filter_function(self, msg):
        print('Here is msg.value')
        print(msg.value)
        print(msg.target.value)
        print('filter_function')
        self.options = list(filter(lambda x: msg.value in str(x['label']).lower(), self.initial_options))
```

In version 0.1.1 there is no longer a value for msg.value. I assume this probably had to do with either the change related to focus or blur?

**Comment by elimintz** [comment]
Thank you for flagging this. There is a bug in version 0.1.1

In version 0.1.0 msg.value would have always been '' (the empty string). In keyboard events, you would need to look at msg.key_data which is a dictionary with information about the key pressed. If you press 'g' it looks like this:
```python
{'altKey': False, 'ctrlKey': False, 'shiftKey': False, 'metaKey': False, 'code': 'KeyG', 'key': 'g', 'location': 0, 'repeat': False} 
```

The reason it is not working now is because of a bug I introduced in version 0.1.1 that made msg.value a dictionary and did not provide msg.key_data. That bug is now fixed for version 0.1.2

Let me know if you need the version to come out quickly or it can wait till the end of the week.

**Comment by knoxvilledatabase** [comment]
Thank you for fixing this. I do have a project pending on this fix so the sooner the better because it means we can go live as soon as its released.

**Comment by elimintz** [comment]
Ok, will have a new version out by end of day tomorrow.

For your consideration, if you have created components (like QSelectWithFilter) perhaps you would be willing to share them and I could add them to the package? This looks like something many people could use.

**Comment by knoxvilledatabase** [comment]
Tomorrow will work out perfectly. Sure, we don't mind sharing components, should I share them here under issues?

**Comment by elimintz** [comment]
Thank you. Yes, just open an issue with them.

**Comment by elimintz** [comment]
@knoxvilledatabase New version, 0.1.2, is out. Please let me know if this solved the problem.

**Comment by knoxvilledatabase** [comment]
Awesome, I will give this a shot this afternoon, thank you!
